name: lifecycle_widget
description: "A widget that emulates the lifecycle of an Activity/ViewController of mobile platforms"
version: 1.0.0
homepage: https://github.com/ilpeppone7/lifecycle_widget.git
repository: https://github.com/ilpeppone7/lifecycle_widget.git

environment:
  sdk: ^3.0.0
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0